version: '3.3'

volumes:
  postgres_volume:
  static_volume:
  media_volume:

services:
  
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  backend:
    container_name: foodgram_backend
    image: permanganatoff/foodgram_backend
    env_file: ./.env
    volumes:
      - static_volume:/app/backend_static
      - media_volume:/app/backend_media
    depends_on:
      - db
  
  frontend:
    container_name: foodgram_frontend
    image: permanganatoff/foodgram_frontend
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - db
      - backend
  
  gateway:
    container_name: foodgram_gateway
    image: permanganatoff/foodgram_gateway
    ports:
      - 9006:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/backend_media
    depends_on:
      - backend
      - frontend