# Generated by Django 4.2.6 on 2023-10-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure_unit',
            new_name='measurement_unit',
        ),
    ]
