# Generated by Django 4.2.6 on 2023-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_measure_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='backend_media/', verbose_name='dish image'),
        ),
    ]
